### ISSUE TITLE
Encountered an error downloading post

### ISSUE THREAD

**Issue by 1223334444abc** [bitbybyte/fantiadl#131]
```
Encountered an error downloading post. Skipping...
Traceback (most recent call last):
  File "G:\fantia\fantiadl-master\fantiadl\models.py", line 233, in download_fanclub
    self.download_post(post_id)
  File "G:\fantia\fantiadl-master\fantiadl\models.py", line 566, in download_post
    if self.download_post_content(post, post_directory, post_title):
  File "G:\fantia\fantiadl-master\fantiadl\models.py", line 484, in download_post_content
    self.download_photo(photo_url, photo_counter, gallery_directory)
  File "G:\fantia\fantiadl-master\fantiadl\models.py", line 437, in download_photo
    self.perform_download(photo_url, filename, use_server_filename=self.use_server_filenames)
  File "G:\fantia\fantiadl-master\fantiadl\models.py", line 402, in perform_download
    self.db.insert_url(url_path)
  File "G:\fantia\fantiadl-master\fantiadl\db.py", line 47, in insert_url
    self.execute("INSERT INTO urls VALUES (?, ?)", (url, int(time.time())))
  File "G:\fantia\fantiadl-master\fantiadl\db.py", line 29, in execute
    self.cursor.execute(query, args)
sqlite3.IntegrityError: UNIQUE constraint failed: urls.url
```

`/posts/1472610`
`/posts/524320`
`/posts/511767`

**Comment by bitbybyte** [comment]
Sounds like we should be using `INSERT IGNORE` for our queries.
